<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
//         \App\Models\User::factory(10)->create();

        DB::table('users')->insert([
            [
                'id' => 1,
                'name' => 'Code One Min',
                'email' => 'codeonemin@gmail.com',
                'password' => Hash::make('codeonemin2023'),

                'level' => 0,
                'description' => 'Admin',

                'company_name'=> 'FPT APTECH',
                'country'=> 'Viêt Nam',
                'street_address'=> '8A Tôn Thất Thuyết',
                'town_city'=> 'Hà Nội',
                'postcode_zip'=> '100000',
                'phone'=> '0999919999',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'Ngô Mạnh Sơn',
                'email' => 'ngomanhson2004txpt@gmail.com',
                'password' => Hash::make('23102004'),

                'level' => 1,
                'description' => null,

                'company_name'=> 'FPT APTECH',
                'country'=> 'Viêt Nam',
                'street_address'=> '8A Tôn Thất Thuyết',
                'town_city'=> 'Hà Nội',
                'postcode_zip'=> '100000',
                'phone'=> '0929999999',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'Hà Hữu Hoàng',
                'email' => 'hahuuhoang732004@gmail.com',
                'password' => Hash::make('07032004'),

                'level' => 2,
                'description' => null,

                'company_name'=> 'FPT APTECH',
                'country'=> 'Viêt Nam',
                'street_address'=> '8A Tôn Thất Thuyết',
                'town_city'=> 'Hà Nội',
                'postcode_zip'=> '100000',
                'phone'=> '0999999959',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'Phùng Văn Vũ',
                'email' => 'phungvu2711@gmail.com',
                'password' => Hash::make('17042004'),

                'level' => 2,
                'description' => null,

                'company_name'=> 'FPT APTECH',
                'country'=> 'Viêt Nam',
                'street_address'=> '8A Tôn Thất Thuyết',
                'town_city'=> 'Hà Nội',
                'postcode_zip'=> '100000',
                'phone'=> '0999999979',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);

        DB::table('blogs')->insert([
            [
                'user_id' => 3,
                'title' => 'Hello everyone. My name is Phung Vu!',
                'slug' => Str::slug('Hello everyone. My name is Phung Vu!'),
                'subtitle' =>'hhh',
                'image' => 'front/img/blog/PhungVu-Blog.jpg',
                'category' => 'TRAVEL',
                'content' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'title' => 'This was one of our first days in Hawaii last week.',
                'slug' => Str::slug('This was one of our first days in Hawaii last week'),
                'subtitle' =>'hhh',
                'image' => 'front/img/blog/blog-2.jpg',
                'category' => 'CodeOneMin',
                'content' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'title' => 'Last week I had my first work trip of the year to Sonoma Valley.',
                'slug' => Str::slug('Last week I had my first work trip of the year to Sonoma Valley'),
                'subtitle' =>'hhh',
                'image' => 'front/img/blog/blog-3.jpg',
                'category' => 'TRAVEL',
                'content' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'title' => 'Happy New Year! I know I am a little late on this post.',
                'slug' => Str::slug('Happy New Year! I know I am a little late on this post'),
                'subtitle' =>'hhh',
                'image' => 'front/img/blog/blog-4.jpg',
                'category' => 'CodeOneMin',
                'content' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'title' => 'Absolue collection. The Lancome team has been one…',
                'slug' => Str::slug('Absolue collection. The Lancome team has been one'),
                'subtitle' =>'hhh',
                'image' => 'front/img/blog/blog-5.jpg',
                'category' => 'MODEL',
                'content' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'title' => 'Writing has always been kind of therapeutic for me.',
                'slug' => Str::slug('Writing has always been kind of therapeutic for me'),
                'subtitle' =>'hhh',
                'image' => 'front/img/blog/blog-6.jpg',
                'category' => 'CodeOneMin',
                'content' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        DB::table('product_comments')->insert([
            [
                'product_id' => 1,
                'user_id' => 4,
                'email' => 'ngomanhson2004txpt@gmail.com',
                'name' => 'Ngô Mạnh Sơn',
                'messages' => 'Nice !',
                'rating' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 1,
                'user_id' => 5,
                'email' => 'RoyBanks@gmail.com',
                'name' => 'Roy Banks',
                'messages' => 'Nice !',
                'rating' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('brands')->insert([
            [
                'name' => 'Adidas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nike',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Puma',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kappa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Li-Ning',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mizuno',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('product_categories')->insert([
            [
                'name' => 'Men',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Women',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('products')->insert([
            [
                'brand_id' => 1,
                'product_category_id' => 1,
                'name' => 'Hat Running Rain-RDY',
                'slug' => Str::slug('Hat Running Rain-RDY'),
                'description' => 'It feels great to run in the rain. This adidas RAIN.RDY cap uses advanced technology to keep rainwater out of your head, allowing you to stay focused in wet conditions. The hat features a baseball-style six-pack and a curved brim, with reflective details that stand out in low light.',
                'content' => '',
                'price' => 20,
                'qty' => 30,
                'discount' => 35,
                'weight' => null,
                'sku' =>  Str::random(8),
                'featured' => true,
                'tag' => 'Hats',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 1,
                'product_category_id' => 1,
                'name' => 'Hat Aerorready',
                'slug' => Str::slug('Hat Aerorready'),
                'description' => 'This adidas half-cap is perfect for tennis courts, training courts and running tracks.AEROREADY technology wicks away moisture to keep you dry and comfortable, while a curved cap protects your eyes from the sun.Silicone logo Embossed with sporty accents.',
                'content' => null,
                'price' => 18,
                'qty' => 25,
                'discount' => 21,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => true,
                'tag' => 'Hats',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 1,
                'product_category_id' => 1,
                'name' => ' Adidas Ultraboost 22',
                'slug' => Str::slug(' Adidas Ultraboost 22'),
                'description' => 'These womens adidas Ultraboost shoes for running have a breathable open knit upper that provides extra ventilation in key sweat zones. Responsive Boost cushioning returns energy with every step. A Continental Rubber outsole gives all the traction you need.',
                'content' => null,
                'price' => 179,
                'qty' => 5,
                'discount' => 219,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => true,
                'tag' => 'Shoes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 2,
                'product_category_id' => 2,
                'name' => ' Nike Air Monarch IV',
                'slug' => Str::slug(' Nike Air Monarch IV'),
                'description' => 'Mens Nike Air Monarch IV  Training Shoe sets you up for comfortable training with durable leather on top for support. A lightweight foam midsole with a full-length encapsultaed Air-Sole unit cushions every stride in the mens sneaker.',
                'content' => null,
                'price' => 159,
                'qty' => 5,
                'discount' => 179,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => true,
                'tag' => 'Shoes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 2,
                'product_category_id' => 2,
                'name' => ' Printed Drawstring Bag',
                'slug' => Str::slug(' Printed Drawstring Bag'),
                'description' => 'Take the Nike Brasilia Printed Drawstring Bag anywhere with ease. With a unique print, this bag features both a large drawstring compartment for storage and a smaller zip front pocket to store all the small stuff.',
                'content' => null,
                'price' => 79,
                'qty' => 5,
                'discount' => 89,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => true,
                'tag' => 'bags',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 1,
                'product_category_id' => 2,
                'name' => ' Adicolor Classic Festival BAG',
                'slug' => Str::slug(' Adicolor Classic Festival BAG'),
                'description' => 'This sleek crossbody bag securely holds the essentials: keys, phone, id and wallet. made of durable ripstop, it features zippered pockets. The iconic trefoil logo on the webbed shoulder strap is a nod to adidas sport heritage. Installation-Surfaces must be clean and free of moisture and contamination.Clean, remove dust, dirt, moisture oil and grease. Cut to desired length then peel off the release liner. DO NOT Stretch this product. Apply to seam, joint, opening, skylight frame, etc. Install or assemble as required. Use Mineral Spirits to clean up this product.Do not apply this product in weather-exposed areas, where temperatures will exceed 190°F.Do not stretch this product during application.Keep out of the reach of children.Do not use where acidic or alkaline chemicals are present.For industrial, professional use only.',
                'content' => null,
                'price' => 88,
                'qty' => 5,
                'discount' => 95,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => true,
                'tag' => 'bags',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 3,
                'product_category_id' => 1,
                'name' => '  Puma Training Desert ',
                'slug' => Str::slug('  Puma Training Desert '),
                'description' => 'Puma Training is safe, sturdy, and slender. Carrying a bottle has never been easy thanks to the Trek Bottle’s angled body design and hinged carrying handle. Double-wall vacuum insulation technology can keep drinks hot or cold for many hours. The firm silicone gaskets placed within the twist cap and lid prevent leaks and maintain temperature. The BPA Free, durable stainless-steel body withstands hard impact against rough surfaces. Equipped for outdoor activities, the Trek Bottle is fit for hiking, biking, and other sports. Begin your journey with LocknLock Trek Bottle.',
                'content' => null,
                'price' => 39,
                'qty' => 5,
                'discount' => 59,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => true,
                'tag' => 'Accessories',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 1,
                'product_category_id' => 1,
                'name' => '  Adidas Metal Water Bottle ',
                'slug' => Str::slug(' Adidas Metal Water Bottle '),
                'description' => 'Sip water at the gym or coffee on the train. this steel water bottle has a double-wall design that keeps hot liquids hot and cold liquids cold for hours. holds 600 milliliters.',
                'content' => null,
                'price' => 42,
                'qty' => 5,
                'discount' => 55,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => true,
                'tag' => 'Accessories',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 1,
                'product_category_id' => 1,
                'name' => '  Superlite Ultraboost Quarter Socks  ',
                'slug' => Str::slug(' Superlite Ultraboost Quarter Socks  '),
                'description' => 'Head into your workout with comfy feet and get a jump start on a solid session. These adidas quarter-length socks combine arch support underfoot with breathable mesh on top. Targeted cushioning holds up to your high-impact efforts, like jump squats and sprints.',
                'content' => null,
                'price' => 12,
                'qty' => 5,
                'discount' => null,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => true,
                'tag' => 'Product',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);

        DB::table('product_images')->insert([
            [
                'product_id' => 1,
                'path' => 'product-1.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 1,
                'path' => 'product-1.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 1,
                'path' => 'product-1.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 1,
                'path' => 'product-1.4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 3,
                'path' => 'product-4.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 3,
                'path' => 'product-4.2.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 3,
                'path' => 'product-4.3.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 3,
                'path' => 'product-4.4.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 2,
                'path' => 'product-2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 2,
                'path' => 'product-2.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'product_id' => 2,
                'path' => 'product-2.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 2,
                'path' => 'product-2.4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 4,
                'path' => 'product-5.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'product_id' => 4,
                'path' => 'product-5.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'product_id' => 4,
                'path' => 'product-5.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'product_id' => 4,
                'path' => 'product-5.4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 5,
                'path' => 'product-6.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 5,
                'path' => 'product-6.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 5,
                'path' => 'product-6.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 5,
                'path' => 'product-6.4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 6,
                'path' => 'product-7.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 6,
                'path' => 'product-7.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 6,
                'path' => 'product-7.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 6,
                'path' => 'product-7.4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 7,
                'path' => 'product-8.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 7,
                'path' => 'product-8.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'product_id' => 7,
                'path' => 'product-8.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 7,
                'path' => 'product-8.4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 8,
                'path' => 'product-9.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 8,
                'path' => 'product-9.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 8,
                'path' => 'product-9.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 8,
                'path' => 'product-9.4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 9,
                'path' => 'product-10.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 9,
                'path' => 'product-10.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 9,
                'path' => 'product-10.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 9,
                'path' => 'product-10.4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);

        DB::table('product_details')->insert([
            [
                'product_id' => 3,
                'size' => '39',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 3,
                'size' => '40',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 3,
                'size' => '41',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 3,
                'size' => '42',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 4,
                'size' => '39',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 4,
                'size' => '40',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 4,
                'size' => '41',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 4,
                'size' => '42',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);


    }
}

