<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
//         \App\Models\User::factory(10)->create();

        DB::table('users')->insert([
            [
                'id' => 1,
                'name' => 'Code One Min',
                'email' => 'codeonemin@gmail.com',
                'password' => Hash::make('codeonemin2023'),

                'level' => 0,
                'description' => 'Admin',

                'company_name'=> 'FPT APTECH',
                'country'=> 'Viêt Nam',
                'street_address'=> '8A Tôn Thất Thuyết',
                'town_city'=> 'Hà Nội',
                'postcode_zip'=> '100000',
                'phone'=> '0999919999',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'Ngô Mạnh Sơn',
                'email' => 'ngomanhson2004txpt@gmail.com',
                'password' => Hash::make('23102004'),

                'level' => 1,
                'description' => null,

                'company_name'=> 'FPT APTECH',
                'country'=> 'Viêt Nam',
                'street_address'=> '8A Tôn Thất Thuyết',
                'town_city'=> 'Hà Nội',
                'postcode_zip'=> '100000',
                'phone'=> '0929999999',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'Hà Hữu Hoàng',
                'email' => 'hahuuhoang732004@gmail.com',
                'password' => Hash::make('07032004'),

                'level' => 2,
                'description' => null,

                'company_name'=> 'FPT APTECH',
                'country'=> 'Viêt Nam',
                'street_address'=> '8A Tôn Thất Thuyết',
                'town_city'=> 'Hà Nội',
                'postcode_zip'=> '100000',
                'phone'=> '0999999959',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'Phùng Văn Vũ',
                'email' => 'phungvu2711@gmail.com',
                'password' => Hash::make('17042004'),

                'level' => 2,
                'description' => null,

                'company_name'=> 'FPT APTECH',
                'country'=> 'Viêt Nam',
                'street_address'=> '8A Tôn Thất Thuyết',
                'town_city'=> 'Hà Nội',
                'postcode_zip'=> '100000',
                'phone'=> '0999999979',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);

        DB::table('blogs')->insert([
            [
                'user_id' => 3,
                'title' => 'Hello everyone. My name is Phung Vu!',
                'slug' => Str::slug('Hello everyone. My name is Phung Vu!'),
                'subtitle' =>'hhh',
                'image' => 'front/img/blog/PhungVu-Blog.jpg',
                'category' => 'TRAVEL',
                'content' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'title' => 'This was one of our first days in Hawaii last week.',
                'slug' => Str::slug('This was one of our first days in Hawaii last week'),
                'subtitle' =>'hhh',
                'image' => 'front/img/blog/blog-2.jpg',
                'category' => 'CodeOneMin',
                'content' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'title' => 'Last week I had my first work trip of the year to Sonoma Valley.',
                'slug' => Str::slug('Last week I had my first work trip of the year to Sonoma Valley'),
                'subtitle' =>'hhh',
                'image' => 'front/img/blog/blog-3.jpg',
                'category' => 'TRAVEL',
                'content' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'title' => 'Happy New Year! I know I am a little late on this post.',
                'slug' => Str::slug('Happy New Year! I know I am a little late on this post'),
                'subtitle' =>'hhh',
                'image' => 'front/img/blog/blog-4.jpg',
                'category' => 'CodeOneMin',
                'content' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'title' => 'Absolue collection. The Lancome team has been one…',
                'slug' => Str::slug('Absolue collection. The Lancome team has been one'),
                'subtitle' =>'hhh',
                'image' => 'front/img/blog/blog-5.jpg',
                'category' => 'MODEL',
                'content' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'title' => 'Writing has always been kind of therapeutic for me.',
                'slug' => Str::slug('Writing has always been kind of therapeutic for me'),
                'subtitle' =>'hhh',
                'image' => 'front/img/blog/blog-6.jpg',
                'category' => 'CodeOneMin',
                'content' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        DB::table('product_comments')->insert([
            [
                'product_id' => 1,
                'user_id' => 4,
                'email' => 'ngomanhson2004txpt@gmail.com',
                'name' => 'Ngô Mạnh Sơn',
                'messages' => 'Nice !',
                'rating' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 1,
                'user_id' => 5,
                'email' => 'RoyBanks@gmail.com',
                'name' => 'Roy Banks',
                'messages' => 'Nice !',
                'rating' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('brands')->insert([
            [
                'name' => 'Adidas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nike',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Puma',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kappa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Li-Ning',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mizuno',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('product_categories')->insert([
            [
                'name' => 'Men',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Women',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('products')->insert([
            [
                'brand_id' => 1,
                'product_category_id' => 2,
                'name' => 'Hat Aerorready',
                'slug' => Str::slug('Hat Aerorready'),
                'description' => 'This adidas half-cap is perfect for tennis courts, training courts and running tracks.AEROREADY technology wicks away moisture to keep you dry and comfortable, while a curved cap protects your eyes from the sun.Silicone logo Embossed with sporty accents.',
                'content' => null,
                'price' => 18,
                'qty' => 25,
                'discount' => 21,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => true,
                'tag' => 'Hats',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 5,
                'product_category_id' => 2,
                'name' => 'Li-Ning ATSQ264 ',
                'slug' => Str::slug('Li-Ning ATSQ264'),
                'description' => 'AT Dry Freeze technology is an advanced drying method, designed to remove moisture from products without affecting their texture. AT Dry Freezes operating process is based on the use of low pressure and low temperature to separate water from the product through evaporation.',
                'content' => null,
                'price' => 132,
                'qty' => 150,
                'discount' => 70,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => false,
                'tag' => 'CLOTHING',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 2,
                'product_category_id' =>1 ,
                'name' => 'Nike Hoops Elite',
                'slug' => Str::slug('Nike Hoops Elite'),
                'description' => 'The name says it all. Premium touches, like densely woven material, an extended zip pull and ventilation holes in the main compartment, add to the classic Hoops Elite graphic. Don forget the front zip pocket and the easy-close drawstring, so you can head to the court and start getting buckets.',
                'content' => null,
                'price' => 67,
                'qty' => 10,
                'discount' => 70,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => true,
                'tag' => 'BAGS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 3,
                'product_category_id' =>1 ,
                'name' => 'PUMA Mens Contrast Pants 2.0',
                'slug' => Str::slug('PUMA Mens Contrast Pants 2.0'),
                'description' => 'We kept it simple for the Contrast Pants. Made with moisturing wicking dryCELL fabric, the Contrast Pants help keep you dry and comfortable. With a stripe side panel in contrast colors and the perfect depth front hand pockets, you be equal parts cool and comfortable.',
                'content' => null,
                'price' => 95,
                'qty' => 5,
                'discount' => null,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => false,
                'tag' => 'CLOTHING',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 3,
                'product_category_id' => 1,
                'name' => 'PUMA TR Bottle',
                'slug' => Str::slug('PUMA TR Bottle'),
                'description' => 'Puma Tr Bottle Sportstyle Bordo 053518 17. Capacious Puma bottle. Screw-on lid and metal clasp with spill protection. A real helper: at workouts, at the gym, on a picnic or even at home. Dishwasher safe.',
                'content' => null,
                'price' => 25,
                'qty' => 38,
                'discount' => 70,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => false,
                'tag' => 'ACCESSORIES',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 5,
                'product_category_id' => 2,
                'name' => 'Li-Ning socks AWSR018',
                'slug' => Str::slug('Li-Ning socks AWSR018'),
                'description' => 'Li-Ning AWSR018-1 sports socks are very foot-friendly, using good sweat-wicking fabric to provide ventilation for all activities. The material is soft, breathable, elastic and has good elasticity. Durable.Comfortable design, does not cause marks on the skin of the feet',
                'content' => null,
                'price' => 12,
                'qty' => 20,
                'discount' => 20,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => false,
                'tag' => 'ACCESSORIES',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 2,
                'product_category_id' => 2,
                'name' => 'Heritage Waistpack',
                'slug' => Str::slug('Heritage Waistpack'),
                'description' => 'Look to the Nike Heritage Waistpack to store the small essentials that dont quite fit in your pockets. An internal zipped stash pocket helps keep things organised and easy to grab. This product is made from at least 65% recycled polyester.',
                'content' => null,
                'price' => 59,
                'qty' => 8,
                'discount' => 90,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => false,
                'tag' => 'BAGS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 5,
                'product_category_id' => 2,
                'name' => 'Women running shoes ARHS008-14',
                'slug' => Str::slug('Women running shoes ARHS008-14'),
                'description' => 'Li-Ning LIGHT FOAM midsole technology uses high-performance olefin copolymer to replace traditional EVA, and is equipped with Li Ning self-developed polymer foaming and bridging system, which can make for finer and more uniform foaming holes, thus reducing density. Reducing the weight of the midsole greatly improves the elasticity of the bottom.',
                'content' => null,
                'price' => 280,
                'qty' => 8,
                'discount' => 300,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => false,
                'tag' => 'SHOES',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 1,
                'product_category_id' => 2,
                'name' => ' Adicolor Classic Festival BAG',
                'slug' => Str::slug(' Adicolor Classic Festival BAG'),
                'description' => 'This sleek crossbody bag securely holds the essentials: keys, phone, id and wallet. made of durable ripstop, it features zippered pockets. The iconic trefoil logo on the webbed shoulder strap is a nod to adidas sport heritage. Installation-Surfaces must be clean and free of moisture and contamination.Clean, remove dust, dirt, moisture oil and grease. Cut to desired length then peel off the release liner. DO NOT Stretch this product. Apply to seam, joint, opening, skylight frame, etc. Install or assemble as required. Use Mineral Spirits to clean up this product.Do not apply this product in weather-exposed areas, where temperatures will exceed 190°F.Do not stretch this product during application.Keep out of the reach of children.Do not use where acidic or alkaline chemicals are present.For industrial, professional use only.',
                'content' => null,
                'price' => 88,
                'qty' => 5,
                'discount' => 95,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => false,
                'tag' => 'bags',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 1,
                'product_category_id' => 1,
                'name' => 'Adidas Ultraboost 22',
                'slug' => Str::slug('Adidas Ultraboost 22'),
                'description' => 'These womens adidas Ultraboost shoes for running have a breathable open knit upper that provides extra ventilation in key sweat zones. Responsive Boost cushioning returns energy with every step. A Continental Rubber outsole gives all the traction you need.',
                'content' => null,
                'price' => 179,
                'qty' => 5,
                'discount' => 219,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => true,
                'tag' => 'Shoes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 5,
                'product_category_id' => 2,
                'name' => 'Women sweatpants AKLR364-2',
                'slug' => Str::slug('Women sweatpants AKLR364-2'),
                'description' => 'Li-Ning sports sweatpants are an indispensable item for teams who are passionate about training or love active style. Each design of the sweatpants emphasizes the selection of breathable, ultra-light materials for more effective training hours. Sewing clothes must not only be careful and meticulous, but also need to be durable, resistant to stretch and good elasticity. Sports sweatpants are also an ideal outfit suggestion when going on a picnic, going out or dating.',
                'content' => null,
                'price' => 175,
                'qty' => 8,
                'discount' => 194,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => false,
                'tag' => 'CLOTHING',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 1,
                'product_category_id' => 1,
                'name' => 'Hat Running Rain-RDY',
                'slug' => Str::slug('Hat Running Rain-RDY'),
                'description' => 'It feels great to run in the rain. This adidas RAIN.RDY cap uses advanced technology to keep rainwater out of your head, allowing you to stay focused in wet conditions. The hat features a baseball-style six-pack and a curved brim, with reflective details that stand out in low light.',
                'content' => '',
                'price' => 20,
                'qty' => 30,
                'discount' => 35,
                'weight' => null,
                'sku' =>  Str::random(8),
                'featured' => true,
                'tag' => 'Hats',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 2,
                'product_category_id' =>2 ,
                'name' => 'Adidas Kaptir',
                'slug' => Str::slug('Adidas Kaptir'),
                'description' => 'Roll through your day in total comfort in these men adidas running-inspired shoes. They feature a Cloudfoam midsole that pillow soft. The knit upper provides a snug and secure fit.',
                'content' => null,
                'price' => 122,
                'qty' => 10,
                'discount' => 130,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => false,
                'tag' => 'SHOES',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 2,
                'product_category_id' => 2,
                'name' => 'Printed Drawstring Bag',
                'slug' => Str::slug('Printed Drawstring Bag'),
                'description' => 'Take the Nike Brasilia Printed Drawstring Bag anywhere with ease. With a unique print, this bag features both a large drawstring compartment for storage and a smaller zip front pocket to store all the small stuff.',
                'content' => null,
                'price' => 79,
                'qty' => 5,
                'discount' => 89,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => true,
                'tag' => 'bags',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 1,
                'product_category_id' => 1,
                'name' => 'Adidas Metal Water Bottle',
                'slug' => Str::slug(' Adidas Metal Water Bottle '),
                'description' => 'Sip water at the gym or coffee on the train. this steel water bottle has a double-wall design that keeps hot liquids hot and cold liquids cold for hours. holds 600 milliliters.',
                'content' => null,
                'price' => 42,
                'qty' => 5,
                'discount' => 55,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => true,
                'tag' => 'Accessories',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 1,
                'product_category_id' => 1,
                'name' => 'Superlite Ultraboost Quarter Socks',
                'slug' => Str::slug(' Superlite Ultraboost Quarter Socks'),
                'description' => 'Head into your workout with comfy feet and get a jump start on a solid session. These adidas quarter-length socks combine arch support underfoot with breathable mesh on top. Targeted cushioning holds up to your high-impact efforts, like jump squats and sprints.',
                'content' => null,
                'price' => 12,
                'qty' => 5,
                'discount' => null,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => false,
                'tag' => 'ACCESSORIES',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 2,
                'product_category_id' => 2,
                'name' => 'Nike Air Monarch IV',
                'slug' => Str::slug('Nike Air Monarch IV'),
                'description' => 'Mens Nike Air Monarch IV  Training Shoe sets you up for comfortable training with durable leather on top for support. A lightweight foam midsole with a full-length encapsultaed Air-Sole unit cushions every stride in the mens sneaker.',
                'content' => null,
                'price' => 159,
                'qty' => 5,
                'discount' => 179,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => false,
                'tag' => 'Shoes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 2,
                'product_category_id' => 2,
                'name' => 'Nike Sportswear Essentials',
                'slug' => Str::slug('Nike Sportswear Essentials'),
                'description' => 'The Nike Sportswear Essentials Cross-Body Bag features 2 zip pockets to let you keep the small stuff organised and easy to grab. The accessory pocket zip pull offers quick access to smaller items, while an adjustable strap and buckle provide an easy-on-and-off fit. This product is made from at least 50% recycled polyester fibres.',
                'content' => null,
                'price' => 40,
                'qty' => 20,
                'discount' => 77,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => false,
                'tag' => 'Shoes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 6,
                'product_category_id' => 1,
                'name' => 'Wave Rider 27',
                'slug' => Str::slug('Wave Rider 27'),
                'description' => 'Get a wave of energy with this shoe offering impressive cushioning and energy return. The MIZUNO WAVE combines cushioning and stability with a propulsive feeling and support for smooth transiton of weight. Moreover, the MIZUNO ENERZY FOAM loaded throughout the midsole also enhances the shoe‘s cushioning and energy return. The new upper structure gently envelops the foot and the shoe‘s overall weight has been lightened by five grams. • MIZUNO ENERZY FOAM - MIZUNO ENERZY, which provides amazing cushioning and energy return, is placed throughout the entire midsole. • MIZUNO WAVE - In addition to providing both cushioning and stability, the WAVE PLATE supports forward propulsion and smooth weight transition.',
                'content' => null,
                'price' => 344,
                'qty' => 20,
                'discount' => 387,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => false,
                'tag' => 'Shoes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 6,
                'product_category_id' => 1,
                'name' => 'ER 5.5 2IN1 SHORT',
                'slug' => Str::slug('ER 5.5 2IN1 SHORT'),
                'description' => 'Lightweight stretch woven fabric for maximum mobility. Built-in compression tights for lightweight support. Back zip pocket for secure storage. Four back open mesh pockets for storage. Reflective details for better visibility during night run. Interior drawcord for secure fit during run.',
                'content' => null,
                'price' => 82,
                'qty' => 20,
                'discount' => 87,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => false,
                'tag' => 'Shoes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 6,
                'product_category_id' => 2,
                'name' => 'DryLite Visor',
                'slug' => Str::slug('DryLite Visor'),
                'description' => 'Unisex visor - Developed for excellent sun protection. An extremely quick drying and breathable cap with laser cut holes.',
                'content' => null,
                'price' => 29,
                'qty' => 20,
                'discount' => 30,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => false,
                'tag' => 'HATS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 1,
                'product_category_id' => 2,
                'name' => 'Adidas Lite Racer Adapt',
                'slug' => Str::slug('Adidas Lite Racer Adapt'),
                'description' => 'Easy, comfortable style. These men adidas running-inspired shoes have a slip-on build secured by an elastic top strap. A Cloudfoam midsole cushions every single step.',
                'content' => null,
                'price' => 298,
                'qty' => 30,
                'discount' => 302,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => false,
                'tag' => 'Shoes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 1,
                'product_category_id' => 1,
                'name' => 'ID BACKPACK 4ATHLTS',
                'slug' => Str::slug('ID BACKPACK 4ATHLTS'),
                'description' => 'Never underestimate the power of great gear to make your day better. With pockets galore and options to strap still more stuff to the sides, this adidas backpack helps you get organised and out the door faster. For training, work, school or even an impromptu weekend away, it the one. Made with a series of recycled materials, and at least 40% recycled content, this product represents just one of our solutions to help end plastic waste.',
                'content' => null,
                'price' => 122,
                'qty' => 10,
                'discount' => 130,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => false,
                'tag' => 'BAGS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 3,
                'product_category_id' => 1,
                'name' => 'Puma S Backpack Putty Beige',
                'slug' => Str::slug('Puma S Backpack Putty Beige'),
                'description' => 'Puma S Backpack Putty Beige Backpack is made of high quality fabric that is durable during use. The stitching of the backpack is very solid and meticulous to ensure satisfaction even for the most demanding customers. The prominent Puma brand name logo motif creates its own highlight.
                                    The backpack has a spacious compartment that helps you to organize scientifically and rationally the necessary items you need to carry with you.
                                    Puma backpacks are uniquely designed for you to enjoy using when going out, traveling, going to school or work... Simple colors are easy to combine with many other outfits according to your preferences.',
                'content' => null,
                'price' => 282,
                'qty' => 10,
                'discount' => 290,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => false,
                'tag' => 'BAGS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 3,
                'product_category_id' => 1,
                'name' => 'Adidas Grand Court',
                'slug' => Str::slug('Adidas Grand Court'),
                'description' => 'Iconic style born on the hardcourt but built for the streets. These men sneakers have a durable synthetic leather upper so you can wear them every day of the week. A Cloudfoam Comfort sockliner elevates comfort, while the rubber outsole grips the ground to keep you moving.',
                'content' => null,
                'price' => 269,
                'qty' => 10,
                'discount' => 290,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => false,
                'tag' => 'Shoes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('product_images')->insert([
            [
                'product_id' => 1,
                'path' => 'product-1.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 1,
                'path' => 'product-1.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 1,
                'path' => 'product-1.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 1,
                'path' => 'product-1.4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 2,
                'path' => 'product-2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 2,
                'path' => 'product-2.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 2,
                'path' => 'product-2.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 3,
                'path' => 'product-3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 3,
                'path' => 'product-3.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 3,
                'path' => 'product-3.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 3,
                'path' => 'product-3.4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 4,
                'path' => 'product-4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 4,
                'path' => 'product-4.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 4,
                'path' => 'product-4.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 5,
                'path' => 'product-5.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 5,
                'path' => 'product-5.2.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 6,
                'path' => 'product-6.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 6,
                'path' => 'product-6.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 6,
                'path' => 'product-6.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 6,
                'path' => 'product-6.4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 7,
                'path' => 'product-7.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 7,
                'path' => 'product-7.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 7,
                'path' => 'product-7.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 7,
                'path' => 'product-7.4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 8,
                'path' => 'product-8.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 8,
                'path' => 'product-8.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 8,
                'path' => 'product-8.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 8,
                'path' => 'product-8.4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 9,
                'path' => 'product-9.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 9,
                'path' => 'product-9.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 9,
                'path' => 'product-9.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 9,
                'path' => 'product-9.4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'product_id' => 10,
                'path' => 'product-10.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 10,
                'path' => 'product-10.2.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 10,
                'path' => 'product-10.3.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 10,
                'path' => 'product-10.4.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 11,
                'path' => 'product-11.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 11,
                'path' => 'product-11.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 11,
                'path' => 'product-11.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 11,
                'path' => 'product-11.4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 12,
                'path' => 'product-12.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 12,
                'path' => 'product-12.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 12,
                'path' => 'product-12.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 12,
                'path' => 'product-12.4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 13,
                'path' => 'product-13.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 13,
                'path' => 'product-13.2.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 13,
                'path' => 'product-13.3.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 13,
                'path' => 'product-13.4.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 14,
                'path' => 'product-14.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 14,
                'path' => 'product-14.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 14,
                'path' => 'product-14.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 14,
                'path' => 'product-14.4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 15,
                'path' => 'product-15.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 15,
                'path' => 'product-15.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 15,
                'path' => 'product-15.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 15,
                'path' => 'product-15.4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 16,
                'path' => 'product-16.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 16,
                'path' => 'product-16.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 16,
                'path' => 'product-16.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 16,
                'path' => 'product-16.4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 17,
                'path' => 'product-17.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 17,
                'path' => 'product-17.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 17,
                'path' => 'product-17.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 17,
                'path' => 'product-17.4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 18,
                'path' => 'product-18.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 18,
                'path' => 'product-18.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 18,
                'path' => 'product-18.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 18,
                'path' => 'product-18.4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 19,
                'path' => 'product-19.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 19,
                'path' => 'product-19.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 19,
                'path' => 'product-19.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 19,
                'path' => 'product-19.4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 20,
                'path' => 'product-20.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 20,
                'path' => 'product-20.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 20,
                'path' => 'product-20.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 20,
                'path' => 'product-20.4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 21,
                'path' => 'product-21.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 21,
                'path' => 'product-21.2.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 22,
                'path' => 'product-22.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 22,
                'path' => 'product-22.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 22,
                'path' => 'product-22.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 22,
                'path' => 'product-22.4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 23,
                'path' => 'product-23.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 23,
                'path' => 'product-23.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 23,
                'path' => 'product-23.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 23,
                'path' => 'product-23.4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 24,
                'path' => 'product-24.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 24,
                'path' => 'product-24.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 24,
                'path' => 'product-24.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 25,
                'path' => 'product-25.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 25,
                'path' => 'product-25.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 25,
                'path' => 'product-25.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 25,
                'path' => 'product-25.4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('product_details')->insert([
            [
                'product_id' => 2,
                'size' => 'M',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 2,
                'size' => 'L',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 2,
                'size' => 'XS',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 2,
                'size' => 'XL',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 4,
                'size' => 'M',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 4,
                'size' => 'L',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 4,
                'size' => 'XL',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 8,
                'size' => 'M',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 8,
                'size' => 'L',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 8,
                'size' => 'XL',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 10,
                'size' => '38',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 10,
                'size' => '39',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 10,
                'size' => '40',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 10,
                'size' => '41',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 10,
                'size' => '42',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 11,
                'size' => 'S',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 11,
                'size' => 'L',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 11,
                'size' => 'XL',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 13,
                'size' => '38',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 13,
                'size' => '39',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 13,
                'size' => '40',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 13,
                'size' => '42',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 17,
                'size' => '38',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 17,
                'size' => '39',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 17,
                'size' => '40',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 17,
                'size' => '42',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 17,
                'size' => '45',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 19,
                'size' => '40',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 19,
                'size' => '42',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 19,
                'size' => '43',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 19,
                'size' => '44',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 19,
                'size' => '45',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 20,
                'size' => 'M',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 20,
                'size' => 'L',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 20,
                'size' => 'XS',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 20,
                'size' => 'XL',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 22,
                'size' => '38',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 22,
                'size' => '39',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 22,
                'size' => '40',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 22,
                'size' => '42',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 25,
                'size' => '40',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 25,
                'size' => '42',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 25,
                'size' => '43',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 25,
                'size' => '44',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 25,
                'size' => '45',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}

